// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type Tree struct {
	Base BaseTree `json:"base"`
}

type BaseTree struct {
	Id int `json:"id"`
}
