// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type BaseTree struct {
	Id int `json:"id"`
}

type User struct {
	Username string `json:"username"`
}
