// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type CreateGroupBase struct {
	Base string `json:"base"`
}

type CreateUserBase struct {
	Name string `json:"name"`
}

type Response struct {
	Message string `json:"message"`
}

type HelloRequest struct {
	Name string `path:"name"`
}
