// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type Response struct {
	Message string `json:"message"`
}

type HelloRequest struct {
	Name string `path:"name"`
}
